### ISSUE TITLE
tx data to wallet for signing

### ISSUE THREAD

**Issue by DougAnderson444** [jfbeats/ArweaveWalletConnector#4]
https://github.com/jfbeats/ArweaveWalletConnector/blob/c45202071604e9ad85813b6f7a214a2a9d64a154/src/ArweaveWebWallet.ts#L78

Hey JF, not sure if you've considered this yet, but I've been thinking that [Transferring](https://developer.mozilla.org/en-US/docs/Glossary/Transferable_objects) the data buffer over to the wallet for signing might be the fastest/most efficient way to do this.

Transfers can be done in `.postMessage(message , [transferable object])` so it should work well with iframe postmessages too

**Comment by jfbeats** [comment]
Data is not needed for signing and is not sent at all for now. It would just be for the wallet provider to try to display what the data is about in its interface before confirming the tx. It may change but, currently, the dapp is in charge of uploading to the gateway so you would need to transfer it back and add logic to restore the tx object because the data and chunks probably share the same memory.

If wallet providers eventually become responsible for the upload (because of their integration to bundling networks) the best bet might be to implement a transfer similar to arweave chunked uploading but between the dapp and wallet. That way you don't assume that the dapp has the full data already allocated in memory

Could be useful for other functions but, for asymmetric cryptography, most of the signing and decrypting is done through short hashes and we tested the perf impact of message passing to be negligible. Best to avoid making the original data disappear in case the dapp still needs it
